package by.ittc.project.navigation.factory;

public enum Commands {
	GET_REGISTRATION, REGISTRATION, AUTHENTICATION, SIGN_OUT, GET_USER, GET_USERS, GET_ADD_SERVICE, ADD_SERVICE, GET_SERVICE, GET_SERVICES, UPDATE_SERVICE, DELETE_SERVICE, SUBSCRIBE_COMMAND, CONFIRM_STATUS, ACTIVATE_STATUS, BLOCK_STATUS
}
